"""
PDF Preview Engine - Canvas Rendering & Document View.

This module provides PDF rendering capabilities for Tkinter applications by
integrating PyMuPDF (fitz) and Pillow (PIL). It converts raw PDF binary data
into rasterized images, displays them sequentially on a scrollable canvas,
and handles dynamic theme background updates.

Author: Anthony Davi <anthonyvieira789@gmail.com>
"""

import tkinter as tk

from PIL import Image, ImageTk
import pymupdf as fitz

class PDFPreviewer:
    """Handles the rendering of PDF bytes onto a Tkinter Canvas.

    This component acts as a bridge between the raw PDF binary data generated by
    the Model and the visual Canvas widget in the View. It uses PyMuPDF (fitz)
    to rasterize PDF pages into images.

    Attributes:
        canvas (tk.Canvas): The canvas widget where PDF pages are drawn.
        current_images (list): Holds references to ImageTk objects to prevent them
            from being garbage-collected by Python, which would cause them to vanish.
    """

    def __init__(self, canvas: tk.Canvas):
        """Initializes the previewer with a reference to the target canvas.

        Args:
            canvas (tk.Canvas): The UI element designated for rendering images.
        """
        self.canvas = canvas
        self.current_images = [] 

    def set_theme(self, theme_name: str):
        """Updates the canvas background based on the current theme.

        Args:
            theme_name (str): The theme name ("dark" or "light").
        """
        if theme_name == "dark":
            self.canvas.config(bg="#2d2d2d")
        else:
            self.canvas.config(bg="#e0e0e0")

    def render_pdf(self, pdf_bytes: bytes):
        """Converts PDF bytes into images and displays them sequentially on the canvas.

        Iterates through all pages in the PDF data, rasterizes them at 100 DPI,
        converts them to Tkinter-compatible images, and places them vertically
        on the canvas. It also adjusts the canvas scroll region dynamically.

        Args:
            pdf_bytes (bytes): The raw binary content of a PDF file.

        Raises:
            Exception: If PyMuPDF fails to open or parse the stream. Handled gracefully
                by printing to stdout to avoid crashing the UI.
        """
        self.canvas.delete("all")
        self.current_images.clear()

        if not pdf_bytes:
            return

        try:
            doc = fitz.open(stream=pdf_bytes, filetype="pdf")
            y_offset = 20  
            max_width = 0  

            for page in doc:
                pix = page.get_pixmap(dpi=100)  
                img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                tk_img = ImageTk.PhotoImage(img)
                
                self.current_images.append(tk_img)
                self.canvas.create_image(20, y_offset, anchor="nw", image=tk_img)
                
                y_offset += pix.height + 20
                if pix.width > max_width:
                    max_width = pix.width

            self.canvas.config(scrollregion=(0, 0, max_width + 40, y_offset))
            
        except Exception as e:
            print(f"Rendering error: {e}")